"""Notion Export MCP server.

Tools: notion.export_page

Falls back to markdown artifact if Notion API is unavailable.
"""

from __future__ import annotations

import os
from typing import Any

from mcp_servers.common.server import is_mock_mode, mock_response

MOCK_MARKDOWN = """# NYC Business Trip
**Jan 15 – Jan 17, 2026**

## Flights
- ✈️ SFO → JFK · United UA 234 · 8:00 AM
- ✈️ JFK → SFO · United UA 891 · 6:00 PM (Jan 17)

## Hotel
- 🏨 The Standard, High Line · 2 nights · $342

## Dining
- 🍽 Le Bernardin · Jan 15, 7:30 PM · 2 guests

## Itinerary Highlights
1. Central Park morning walk
2. Meetings at Midtown office (10 AM – 3 PM)
3. High Line walk to dinner

---
*Generated by Travel Butler*
"""


async def handle_tool(method: str, payload: dict[str, Any]) -> dict[str, Any]:
    """Handle notion.export_page."""
    if method == "export_page":
        return await _export_page(payload)
    raise ValueError(f"Unknown method: notion.{method}")


async def _export_page(payload: dict[str, Any]) -> dict[str, Any]:
    trip_id = payload.get("trip_id", "")

    if is_mock_mode():
        return mock_response({
            "page_id": "notion_mock_page_001",
            "url": "https://notion.so/mock-travel-butler-page",
            "markdown_fallback": MOCK_MARKDOWN,
        })

    # Try Notion API first, fall back to markdown
    notion_key = os.getenv("NOTION_API_KEY", "")
    if not notion_key:
        return {
            "fallback": True,
            "format": "markdown",
            "content": MOCK_MARKDOWN,
            "message": "Notion API key not configured. Returning markdown artifact.",
        }

    # TODO: Real Notion API page creation
    import httpx

    try:
        async with httpx.AsyncClient() as client:
            resp = await client.post(
                "https://api.notion.com/v1/pages",
                json={
                    "parent": {"type": "workspace", "workspace": True},
                    "properties": {
                        "title": [{"text": {"content": f"Trip: {trip_id}"}}]
                    },
                    # TODO: Build proper Notion blocks from trip data
                },
                headers={
                    "Authorization": f"Bearer {notion_key}",
                    "Notion-Version": "2022-06-28",
                },
            )
            resp.raise_for_status()
            data = resp.json()
            return {"page_id": data["id"], "url": data["url"]}
    except Exception:
        # Fallback to markdown
        return {
            "fallback": True,
            "format": "markdown",
            "content": MOCK_MARKDOWN,
            "message": "Notion API failed. Returning markdown artifact.",
        }
