"""Apple Wallet .pkpass generation.

TODO: Real signing requires Apple WWDR cert + pass type certificate.
This module generates a valid-looking mock .pkpass ZIP for development.
"""

from __future__ import annotations

import io
import json
import zipfile
import logging

logger = logging.getLogger("travel_butler.wallet")


async def generate_pkpass(user_id: str, trip_id: str) -> bytes:
    """Generate a mock .pkpass file for development.

    A real .pkpass is a signed ZIP containing:
      - pass.json (pass definition)
      - manifest.json (SHA1 hashes)
      - signature (PKCS7)
      - icon.png, logo.png, etc.

    This mock version includes pass.json + manifest.json without real signing.
    Use wallet_testing.md for iOS Simulator instructions.
    """
    pass_json = {
        "formatVersion": 1,
        "passTypeIdentifier": "pass.com.example.travelbutler",
        "serialNumber": f"tb-{trip_id}-{user_id[:8] if len(user_id) > 8 else user_id}",
        "teamIdentifier": "MOCK_TEAM",
        "organizationName": "Travel Butler",
        "description": "Trip Pass",
        "foregroundColor": "rgb(255, 255, 255)",
        "backgroundColor": "rgb(99, 102, 241)",
        "labelColor": "rgb(198, 202, 254)",
        "boardingPass": {
            "transitType": "PKTransitTypeAir",
            "headerFields": [
                {"key": "date", "label": "DATE", "value": "Jan 15, 2026"}
            ],
            "primaryFields": [
                {"key": "origin", "label": "SFO", "value": "San Francisco"},
                {"key": "destination", "label": "JFK", "value": "New York"},
            ],
            "secondaryFields": [
                {"key": "flight", "label": "FLIGHT", "value": "UA 234"},
                {"key": "gate", "label": "GATE", "value": "B22"},
            ],
            "auxiliaryFields": [
                {"key": "hotel", "label": "HOTEL", "value": "The Standard"},
                {"key": "dinner", "label": "DINNER", "value": "Le Bernardin 7:30 PM"},
            ],
            "backFields": [
                {
                    "key": "info",
                    "label": "Trip Details",
                    "value": "Generated by Travel Butler. This is a mock pass for development.",
                }
            ],
        },
    }

    # Build ZIP in memory
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        pass_bytes = json.dumps(pass_json, indent=2).encode("utf-8")
        zf.writestr("pass.json", pass_bytes)

        # Mock manifest (real one needs SHA1 hashes + PKCS7 signature)
        manifest = {"pass.json": "mock-sha1-hash"}
        zf.writestr("manifest.json", json.dumps(manifest).encode("utf-8"))

        # TODO: Add icon.png, logo.png, signature with real Apple certs
        # zf.writestr("signature", real_pkcs7_signature)

    logger.info("Generated mock .pkpass for trip %s user %s", trip_id, user_id)
    return buf.getvalue()
